// donner de tout les hotels
const data_base = [
  {
    id: 1,
    name: "Big Burger",
    img: "../images/plat/burger.webp",
    prix: 2000,
    popularity: 5,
    available: true,
    stock: 12,
    cat: "Italien",
    proteine: 2,
    glucide: 7,
    lipide: 3,
    dlc: "25 Janvier 2025",
    ingredient: [1, 2, 3, 4],
  },
  {
    id: 2,
    name: "Pack café",
    img: "../images/plat/petitdej.webp",
    popularity: 2,
    prix: 5000,
    available: true,
    stock: 12,
    cat: "Français",
    proteine: 1,
    glucide: 2,
    lipide: 8,
    ingredient: [1, 2, 3],
    dlc: "25 Janvier 2025",
  },
  {
    id: 3,
    name: "Steak américain",
    img: "../images/plat/pork-steak.webp",
    popularity: 3,
    prix: 10000,
    available: false,
    stock: 0,
    cat: "Américain",
    proteine: 7,
    glucide: 5,
    lipide: 4,
    ingredient: [1, 2, 3],
    dlc: "25 Janvier 2025",
  },
  {
    id: 4,
    name: "Tacos poulet",
    img: "../images/plat/chicken_tacos.webp",
    popularity: 5,
    prix: 10500,
    available: true,
    stock: 20,
    cat: "Américain",
    proteine: 5,
    glucide: 2,
    lipide: 1,
    ingredient: [4, 2, 3, 5],
    dlc: "25 Janvier 2025",
  },
  {
    id: 5,
    name: "Pizza Fromage",
    img: "../images/plat/pizza_fromage.webp",
    popularity: 2,
    prix: 20000,
    available: true,
    stock: 1,
    cat: "Italien",
    proteine: 8,
    glucide: 2,
    lipide: 1,
    ingredient: [1, 2, 3],
    dlc: "25 Janvier 2025",
  },
  {
    id: 6,
    name: "Pizza poulet",
    img: "../images/plat/pizza_poulet.webp",
    popularity: 3,
    prix: 20000,
    available: false,
    stock: 0,
    cat: "Français",
    proteine: 7,
    glucide: 5,
    lipide: 4,
    ingredient: [2, 4, 3],
    dlc: "25 Janvier 2025",
  },
  {
    id: 7,
    name: "Frite de poulet",
    img: "../images/plat/poulet_frite.webp",
    popularity: 1,
    prix: 50000,
    available: true,
    stock: 17,
    cat: "Américain",
    proteine: 4,
    glucide: 5,
    lipide: 2,
    ingredient: [1, 2, 3, 5],
    dlc: "25 Janvier 2025",
  },
  {
    id: 8,
    name: "Salade de poulet",
    img: "../images/plat/salade.webp",
    popularity: 4,
    prix: 30000,
    available: true,
    stock: 5,
    cat: "Chinois",
    proteine: 1,
    glucide: 8,
    lipide: 6,
    ingredient: [1, 2, 3, 6],
    dlc: "25 Janvier 2025",
  },
  {
    id: 9,
    name: "Sandwitch",
    img: "../images/plat/sandwitch.webp",
    popularity: 3,
    prix: 15000,
    available: true,
    stock: 4,
    cat: "Français",
    proteine: 2,
    glucide: 1,
    lipide: 3,
    ingredient: [1, 4, 3],
    dlc: "25 Janvier 2025",
  },
  {
    id: 10,
    name: "Pizza",
    img: "../images/plat/seafood-pizza.webp",
    popularity: 3,
    prix: 10000,
    available: false,
    stock: 0,
    cat: "Italien",
    proteine: 1,
    glucide: 2,
    lipide: 8,
    ingredient: [1, 2, 3],
    dlc: "25 Janvier 2025",
  },
  {
    id: 11,
    name: "Tacos",
    img: "../images/plat/tacos.webp",
    popularity: 2,
    prix: 10000,
    available: false,
    stock: 0,
    cat: "Gastronomique",
    proteine: 5,
    glucide: 1,
    lipide: 3,
    ingredient: [1, 2, 3, 6],
    dlc: "25 Janvier 2025",
  },
];

// donner des plats disponibles
const matierPremier = [
  {
    id: 1,
    name: "Farine",
    img: `../images/ingredients/farine.webp`,
    type: "Riz",
  },
  {
    id: 2,
    name: "Jambon",
    img: "../images/ingredients/jambon.webp",
    type: "Charcuterie",
  },
  {
    id: 3,
    name: "Sausice",
    img: "../images/ingredients/sausice.webp",
    type: "Charcuterie",
  },
  {
    id: 4,
    name: "Oignon",
    img: "../images/ingredients/Oignon.webp",
    type: "Légume",
  },
  {
    id: 5,
    name: "Patate",
    img: "../images/ingredients/patate.webp",
    type: "Légume",
  },
  {
    id: 6,
    name: "Salade",
    img: "../images/ingredients/salade.webp",
    type: "Légume",
  },
];
